### PR TITLE
elasticsearch output plugin: function as config value #135

### PR DESCRIPTION
**Pull request by rucciva**
#135

### CODE REVIEW

**Comment by otisg** [comment]
Are these changes backwards compatible?

**Comment by rucciva** [comment]
Unless i am missing the existnce of config keys which have already accept a function before, then i think it is backward compatible

**Comment by rucciva** [comment]
Hi, any news on this?

**Comment by megastef** [comment]
Hi @rucciva - I've got a problem. It looks the elasticsearch output is not working as expected anymore. 

``` 
Possibly Unhandled Rejection at: Promise  TypeError: url.indexOf is not a function
    at Logsene.setUrl (/usr/local/lib/node_modules/@sematext/logagent/node_modules/logsene-js/index.js:223:11)
    at new Logsene (/usr/local/lib/node_modules/@sematext/logagent/node_modules/logsene-js/index.js:185:8)
    at OutputElasticsearch.getLogger (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output/elasticsearch.js:71:18)
    at OutputElasticsearch.indexData (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output/elasticsearch.js:55:21)
    at OutputElasticsearch.eventHandler (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output/elasticsearch.js:119:8)
    at LogEventEmitter.emit (/usr/local/lib/node_modules/@sematext/logagent/node_modules/eventemitter3/index.js:151:33)
    at LogEventEmitter.parsedEvent (/usr/local/lib/node_modules/@sematext/logagent/lib/core/logEventEmitter.js:17:8)
    at /usr/local/lib/node_modules/@sematext/logagent/bin/logagent.js:365:33
```

The output config is pretty standard: 
```
output:
  logsene:
    module: elasticsearch
    url: https://logsene-receiver.sematext.com:https://logsene-receiver.sematext.com
    index: LOGSENE_TOKEN_HERE
 ```

Do you have an idea, why url is not a string anymore  (having no function indexOf) ?

**Comment by megastef** [comment]
I think this change fixed it: https://github.com/sematext/logagent-js/blob/master/lib/util/config-reducer.js#L6-L8

Somehow the configReducer function assumed there could only be one function in a config but some other functions have been attached to the config. We need to clean up this issue one day...

**Comment by rucciva** [comment]
whoa, i might have missed to realize that token mapper is a function, i am so sorry

maybe
<https://github.com/sematext/logagent-js/blob/master/lib/plugins/output/elasticsearch.js#L98-L100>

should be done first before [config reducer](https://github.com/sematext/logagent-js/blob/b73016230ba1347c6ec725b9c1fc45f4ace80b21/lib/plugins/output/elasticsearch.js#L96)

**Pull request merged**
