### PR TITLE
[WIP] add eslintrc config, fix various issues identified by eslint

### PR DESCRIPTION
**Pull request by DanCech**
This isn't complete yet, but I wanted to get your feedback @megastef before going any further with it.

With my own projects I've found it very helpful to use eslint as a sanity check for typos, unused/undefined variables, etc as well as keeping more consistent coding standards.

As I've been writing PRs here it bugged me that I couldn't lint my changes, so I developed a base eslint config by looking at the existing codebase, and took a stab at cleaning up some of the inconsistencies and bugs that running it identified.

There are still a number of issues that I'm not sure how you'd like to resolve, which are:
```
./bin/logagent.js
  216:75  error  'context' is defined but never used            no-unused-vars
  279:26  error  'e' is defined but never used                  no-unused-vars
  284:18  error  'e' is defined but never used                  no-unused-vars
  391:7   error  'logagent' is assigned a value but never used  no-unused-vars

./lib/core/cliArgs.js
  83:42  error  Strings must use singlequote  quotes

./lib/parser/maxmind-update.js
  55:30  error  'stdin' is defined but never used  no-unused-vars

./lib/parser/parser.js
  343:46  error  'result' is defined but never used  no-unused-vars
  469:24  error  'result' is defined but never used  no-unused-vars
  535:32  error  'result' is defined but never used  no-unused-vars

./lib/plugins/input/stdin.js
  18:43  error  'err' is defined but never used  no-unused-vars

./lib/plugins/output/rtail.js
  39:128  error  'err' is defined but never used                   no-unused-vars
  61:9    error  'rtailServer' is assigned a value but never used  no-unused-vars

./lib/plugins/output/stdout.js
  9:55  error  'context' is defined but never used  no-unused-vars

./test/http-receiver/httpserver.js
  14:7  error  'b' is not defined  no-undef

./test/sql-filter-test.js
  48:42  error  'error' is defined but never used  no-unused-vars

./test/test.js
  53:9  error  'la' is assigned a value but never used  no-unused-vars

✖ 16 problems (16 errors, 0 warnings)
```

Anyway, hopefully this is a good point to start from.

### CODE REVIEW

**Comment by megastef** [comment]
Is this compliant to https://www.npmjs.com/package/standard?

**Comment by megastef** [comment]
We have https://github.com/sematext/logagent-js/blob/master/.jshintrc tuned to 'standard'

**Comment by megastef** [comment]
"error  'result' is defined but never used" is annoying, reporting function args as unused - it forces one to remove the arguments from the list. If you need this argument later, we can't see that the function has the argument.
See https://github.com/eslint/eslint/issues/728
I would  add ""no-unused-vars": [2, {"vars": "local", "args": "all"}]"

**Comment by megastef** [comment]
I just want to share the output of "standard": 
```
standard lib/*/*.js
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/stefan/sematext/logagent-js/lib/core/cliArgs.js:19:18: Wrap an immediate function invocation in parentheses.
  /Users/stefan/sematext/logagent-js/lib/core/logSourceToIndexMapper.js:54:3: Expected { after 'if' condition.
  /Users/stefan/sematext/logagent-js/lib/core/logSourceToIndexMapper.js:54:43: Expected '===' and instead saw '=='.
  /Users/stefan/sematext/logagent-js/lib/core/logSourceToIndexMapper.js:56:3: Expected { after 'else'.
  /Users/stefan/sematext/logagent-js/lib/parser/multiLine.js:22:17: A constructor name should not start with a lowercase letter.
  /Users/stefan/sematext/logagent-js/lib/parser/multiLine.js:23:14: Extra space before value for key 'interval'.
  /Users/stefan/sematext/logagent-js/lib/parser/parser.js:77:51: Expected error to be handled.
  /Users/stefan/sematext/logagent-js/lib/parser/parser.js:130:7: Expected { after 'if' condition.
  /Users/stefan/sematext/logagent-js/lib/parser/parser.js:188:103: Object properties must go on a new line if they aren't all on the same line.
  /Users/stefan/sematext/logagent-js/lib/parser/parser.js:283:28: Expected '===' and instead saw '=='.
  /Users/stefan/sematext/logagent-js/lib/parser/parser.js:408:77: Expected '===' and instead saw '=='.
  /Users/stefan/sematext/logagent-js/lib/parser/parser.js:414:50: Expected '!==' and instead saw '!='.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:3:13: Missing space before function parentheses.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:10:31: Missing space before function parentheses.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:11:61: A space is required after ','.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:13:25: Missing space before function parentheses.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:18:22: A space is required after ','.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:21:30: Missing space before function parentheses.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:26:32: Missing space before function parentheses.
  /Users/stefan/sematext/logagent-js/lib/parser/timerEvent.js:32:2: Newline required at end of file but not found.
```

**Comment by megastef** [comment]
Fixed all eslint and standard warnings. So we have a good point to continue. You can call "npm run eslint" and "npm run standard" to check.

**Comment by otisg** [comment]
Thanks for this PR! Can Travis run these for us?

**Comment by megastef** [comment]
Added "precommit" configuration. 
Developers run once:
```
npm run hook-install
```

This installs a local pre-commit hook for git and runs then eslint & standard.

**Pull request merged**
