### PR TITLE
Prevent startup crash while using gelf input

### PR DESCRIPTION
**Pull request by tprobinson**
`this` is the wrong context object inside of that function, changing to `self` has the desired effect.

### CODE REVIEW

**Comment by otisg** [comment]
Thanks @tprobinson 
@megastef looks like date-fns failure, but only with node 0.12 - do we really care to support 0.12?

**Comment by otisg** [comment]
@megastef OK if we merge this?  note the Travis failure.  Looks like it's only with 0.12 which we said we could remove, ja?

**Comment by fbalicchia** [comment]
Hi @otisg 
with the last commit that piece of code was change. at the moment remote host information was retrieved from udp socket.

**Comment by megastef** [comment]
I think the PR is outdated (merge conflict). See https://github.com/sematext/logagent-js/blob/master/lib/plugins/input/gelf.js#L33

**Pull request closed without merging**
