### PR TITLE
Create graygelf in constructor once vs on every call to eventHandler

### PR DESCRIPTION
**Pull request by hkclark**
Here is a Pull Request that fixes the leak with graygelf for me.  Let me know if there are any questions or comments or if I can do anything to help.  Thanks!

### CODE REVIEW

**Comment by otisg** [comment]
Ping @adnanrahic, @megastef can we merge & release?

**Comment by hkclark** [comment]
@adnanrahic Yeah, I almost did this assuming the other was pushed but figured it was better to do them both right off master.  Will do as you suggest... should be sorted in a sec.

**Comment by hkclark** [comment]
@adnanrahic Whew, I should never do this stuff before morning coffee!  But I should have it sorted.  Let me know if you see any issues.  Thanks!

**Comment by adnanrahic** [comment]
Thanks again @hkclark for taking the time to fix this issue. Hope you enjoy using Logagent. Feel free to reach out or open new issues if you come across any bugs. :smile:

**Comment by hkclark** [comment]
@adnanrahic  Terrific!  Thank you so much for the help.  We are looking forward to using logagent.js -- it's got some really great features and a nice, lightweight footprint.  Many thanks!

**Comment by otisg** [comment]
Thank you for your kind words, @hkclark!
According to https://github.com/hkclark this was your first PR on GitHub?  If that's right, 👏.

**Comment by hkclark** [comment]
Yeah, we use a private Github Enterprise and a bunch of other private git repos at work, so I haven't done much on the public side of things. :-)

**Comment by otisg** [comment]
Ah, and I thought we were your first love ;)

**Comment by hkclark** [comment]
LOL :-)

**Pull request merged**
