### PR TITLE
SC-7051: Added GitHub Webhook input plugin

### PR DESCRIPTION
**Pull request by adnanrahic**
Added a new input plugin for Github Webhooks. The input plugin will run as a server and listen for HTTP requests. It will take token and region values from the URL and parse an event object from the GitHub Webhook. The output will send an HTTP request to the Sematext Events API.

### CODE REVIEW

**Comment by megastef** [comment]
We plan more webhooks, which could easily share some code. Therefore I suggest placing them all in `lib/plugins/input/webhooks/` folder. So we can have there a super-class or helper functions in the future.

**Comment by adnanrahic** [comment]
Agreed. I'll work on this today.

**Comment by otisg** [comment]
Is there a /doc/.... for this or ... a separate ticket for it?

**Comment by adnanrahic** [comment]
Yup, I've created a ticket :point_right: SC-7106

**Pull request merged**
