### PR TITLE
Create Cassandra CQL query input plugin #122

### PR DESCRIPTION
**Pull request by fbalicchia**
Hi,
I've prepare Cassandra Input plugin, please review
At the moment seems that Cassandra nodejs-driver is pure js. If It is ok can I leave it in Logagent-js core or is necessary to create an external plugin ?

Thanks

### CODE REVIEW

**Comment by megastef** [comment]
What about the dependency to ‘java’ in package.json - are therd any problems when JRE/JDK is not installed?

**Comment by fbalicchia** [comment]
Opss, messed up a little during merge from a branch

**Comment by otisg** [comment]
Nice, thanks @fbalicchia !
We'll want to add some docs under https://sematext.com/docs/logagent/plugins/

**Comment by fbalicchia** [comment]
Yes, I'm working on it

**Pull request merged**
