### PR TITLE
SC-13832 Update dependencies

### PR DESCRIPTION
**Pull request by PabloB94**

### CODE REVIEW

**Comment by otisg** [comment]
Pablo, question, what can a reviewer really review here?  Unless they can build this sucker and run it through some tests, can they really review this?

**Comment by PabloB94** [comment]
Unless they build it, not really. The point is more to keep people aware of this stuff than to get an actual code review, since this has to be done pretty often and I don't think it's a good practice to only have one person know the state of these repos

**Review by PavaoSemaZornija — APPROVED** [review]
LGTM.

These dependency upgrades were probably done to handle some security vulnerabilities right?

**Comment by PabloB94** [comment]
Yes, these are mostly things flagged by dependabot and NPM audit

**Pull request merged**
