### PR TITLE
Azure eventhub plugin

### PR DESCRIPTION
**Pull request by megastef**

### CODE REVIEW

**Comment by megastef** [comment]
Hi @adnanrahic please check.

**Comment by otisg** [comment]
So this is a new input plugin?  Can we /doc it?

**Comment by adnanrahic** [comment]
I agree we should add it to the docs. Let's make a habit of creating an example config file for every new plugin and adding it to the [plugins docs overview](https://sematext.com/docs/logagent/plugins/) and adding a dedicated page for the plugin, e.g. [ES](https://sematext.com/docs/logagent/output-plugin-aws-elasticsearch/).

**Comment by megastef** [comment]
Added config examples, it includes invalid Azure access keys - so no worries about security pleas.

**Pull request merged**
