### PR TITLE
add error handling for invalid tokens

### PR DESCRIPTION
**Pull request by megastef**
- parsing tokens from url, even when systemd-journal-upload add port and upload in the path 
- blacklist tokens for 5 minutes when indexing in sematext cloud fails

### CODE REVIEW

**Comment by otisg** [comment]
Should invalid token handling be done in some other place, so that it is not limited to just the journald upload plugin?

**Comment by megastef** [comment]
Please don't merge, i'm working on improvements

@otisg blocking invalid tokens: 
- yes this functionality is also useful for other http receivers
- we can try to wrap the functionality in a helper class but the http handler itself must reject the http call with 4xx status code. So we will always have some specific code for it. I'll try to refactor the code.

**Comment by megastef** [comment]
@otisg @adnanrahic I think this PR is complete and contains all journald receiver improvements. 
- using [Sematext Common Schema](https://sematext.com/docs/tags/common-schema/)
- helper class to blacklist tokens, so we can use it in Heroku, Cloudfoundry, webhooks receivers etc. 

Example output using common schema in YAML format: 
```
__cursor:          s=d5c6de465016430b8b47552b08d35c07;i=36893d;b=671303be039c460f898b637b5bca7697;m=4f8ec78ad23;t=58635495306a8;x=f88836c4f568bc1f
_boot_id:          671303be039c460f898b637b5bca7697
_transport:        syslog
syslog_identifier: sshd
_comm:             sshd
_exe:              /usr/sbin/sshd
_cap_effective:    3fffffffff
_systemd_unit:     ssh.service
_systemd_slice:    system.slice
_machine_id:       400518d7368b56325877a28f6f43d32c
syslog_pid:        4196
message:           Disconnected from 218.92.0.208 port 47994 [preauth]
os: 
  host: docker-demo
facility:          undefined
severity:          info
process: 
  pid:    4196
  uid:    0
  gid:    0
  cmd:    sshd: root [priv]   
  cgroup: /system.slice/ssh.service
```

**Comment by megastef** [comment]
I moved all formatting code for Sematext Common Schema into journald-format output filter. 
So please don't merge ...

**Pull request merged**
