### PR TITLE
Changed mqtt-broker input plugin to typescript

### PR DESCRIPTION
**Pull request by nitinbansal1989**

### CODE REVIEW

**Comment by megastef** [comment]
Is typescript specific for node versions? See e.g. https://github.com/sematext/logagent-js/blob/91109a65d838a017023afed27123e0b292c8d06b/typings.json#L3

Would this PR limit LA to Node 7? Today LA works with Node 4,6,8,10.

**Comment by megastef** [comment]
IF we take the PR, then we should consider giving the plugin a different name. Or @nitinbansal1989 you can release it as external module separately distributed on NPM like: https://www.npmjs.com/package/logagent-input-logstash-stats

Thre are many other plugins released as separate NPM modules. See https://www.npmjs.com/search?q=logagent

I don't see a problem adding the new MQTT plugin to the documentation:  https://sematext.com/docs/logagent/plugins/ 
https://github.com/sematext/docs/tree/master/docs/logagent

**Comment by nitinbansal1989** [comment]
Apologies for the major shift but the focus for making the plugin as a TS is the change of module from prototype model to Class model, as Class model is supported from Node version 4 and brings some efficiency. Also it brings some static typings and code completions while developing. Not a major concerns though. I didn't change the core functionality of the plugin.
My main target was to add the authentication in this plugin.
Please let me know if i need to do any other change.

**Comment by megastef** [comment]
We added authentication without taking the change for TypeScript. Sorry for the  concerns about portability for various node versions (some users use Logagent on CentOS with old node versions)

Please check changes in commit: https://github.com/sematext/logagent-js/commit/bd118ea128f3e59d7c5a36b186c4484b40341288 

Released, update logagent `npm - -g @sematext/logagent@2.0.125` 

Let us know if it works for you.

**Comment by nitinbansal1989** [comment]
Thanks

**Pull request closed without merging**
