### PR TITLE
Kafka input support

### PR DESCRIPTION
**Pull request by fbalicchia**
Hi, 

I have added kafka input. Instead of use https://www.npmjs.com/package/kafka-node as suggest in #49 I prefer to use kafka-native cause is much align with new Consumer Client API both use https://github.com/edenhill/librdkafka.

On the wire there is  https://github.com/Blizzard/node-rdkafka and IMHO is most flexible respect other two and provide KafkaStream support, but
at the moment i was enable to use client API the for now I choose kafka-native.

From Delivery Semantics point of at the moment The consumer store it position in local file that can be configure then "at-least-once" is respected

Every suggestion are welcome

Thanks for attention

--Filippo

### CODE REVIEW

**Comment by otisg** [comment]
Thanks @fbalicchia !
Is this going to be a bit problematic, as it depends on the shared libs and such, which may or may not exist?
(looks like Travis CI is having problems with exactly this sort of thing)

Similarly, won't this cause problems where one updates librdkafka and inadvertently breaks this kafka input plugin?

Or is this common in Node.js world and people just deal with it?

**Comment by fbalicchia** [comment]
Opps ! sorry @otisg on my branch I haven't enable travis and see that error. On my local machine I use node v8.1.2 instead in .travis file I don't see specify version 8. I'll fix on my branch and after that I'll reopen issue.
Thanks

**Comment by megastef** [comment]
I think we can configure travis to compile the lib.  A separate npm package would be possible for the plugin. Then only Kafka users would need to deal with it. See https://github.com/megastef/logagent-tcp-input/blob/master/README.md for an example.

**Comment by megastef** [comment]
@fbalicchia here is a travis example with enabled C++ compiler: 
https://github.com/sematext/spm-agent-nodejs/blob/master/.travis.yml

I hope this helps to make .travis file for your Kafka plugin. 

In this repository we could add link and documentation for the Kafka plugin.

**Pull request closed without merging**
